#ifndef MAIN_STEPPER_STEPPER_COMMANDS_H_
#define MAIN_STEPPER_STEPPER_COMMANDS_H_

#define STEPPER_COMMAND_NOCOMMAND 0x00
#define STEPPER_COMMAND_FULL_OPEN 0x01
#define STEPPER_COMMAND_FULL_CLOSE 0x02
#define STEPPER_COMMAND_STEP_OPEN 0x03
#define STEPPER_COMMAND_STEP_CLOSE 0x04

#define STEPPER_COMMAND_CALIBRATE 0xF0
#define STEPPER_COMMAND_CALIBRATE_DO_CLOSE 0xF1
#define STEPPER_COMMAND_CALIBRATE_DO_OPEN  0xF2

#endif /* MAIN_STEPPER_STEPPER_COMMANDS_H_ */
