M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Ср 01 ноя 2023 15:39:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-01T15:39:27+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.5197Y-2.6378
X2.9134Y-3.5433
X4.0945Y-2.9921
T0
M30
