M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Чт 14 дек 2023 14:14:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-14T14:14:11+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.5197Y-2.6378
X2.9134Y-3.5433
X4.0945Y-2.9921
T0
M30
