#ifndef MAIN_CONTROLLER_CONTROLLER_STATUS_DEF_H_
#define MAIN_CONTROLLER_CONTROLLER_STATUS_DEF_H_

#define CONTROLLER_STATUS_START_EXECUTE_OPEN  0x01
#define CONTROLLER_STATUS_START_EXECUTE_CLOSE 0x02
#define CONTROLLER_STATUS_END_EXECUTE_OPEN    0x03
#define CONTROLLER_STATUS_END_EXECUTE_CLOSE   0x04
#define CONTROLLER_STATUS_START_FIND_POSITION 0x05
#define CONTROLLER_STATUS_START_CALIBRATION   0x06
#define CONTROLLER_STATUS_END_CALIBRATION     0x07
#define CONTROLLER_STATUS_FAIL_CALIBRATION    0x08
#define CONTROLLER_STATUS_WINDOW_LOCK_OPENED  0x09
#define CONTROLLER_STATUS_TASK_CANCELLED      0x0A
#define CONTROLLER_STATUS_ERROR_RAISED        0x0B
#define CONTROLLER_STATUS_ERROR_CANCELLED     0x0C

#endif /* MAIN_CONTROLLER_CONTROLLER_STATUS_DEF_H_ */
