#ifndef MAIN_CONTROLLER_CONTROLLER_ARGS_DEF_H_
#define MAIN_CONTROLLER_CONTROLLER_ARGS_DEF_H_

#define CONTROLLER_HM_FULL_OPEN		   0x01
#define CONTROLLER_HM_FULL_CLOSE	   0x02
#define CONTROLLER_HM_CALIBRATE		   0x04
#define CONTROLLER_HM_CANCEL_ERROR	   0x05

#endif /* MAIN_CONTROLLER_CONTROLLER_ARGS_DEF_H_ */
