#ifndef MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_
#define MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_

#define FM_COMMAND_ADDRESS__PDU 		        0xA5B2

#define FM_COMMAND_ADDRESS__MM_STEPPER_STATUS 	0x3726

#define FM_COMMAND_ADDRESS__OM_ALARM        	0x5A22
#define FM_COMMAND_ADDRESS__OM_AIR_STATUS       0x9725
#define FM_COMMAND_ADDRESS__OM_NOISE_DATA       0x7745
#define FM_COMMAND_ADDRESS__OM_CHARGE_STATUS    0x9399

#define FM_COMMAND_ADDRESS__HM_COMMAND			0xB724
#define FM_COMMAND_ADDRESS__HM_CHARGE_STATUS	0xC17A

#endif /* MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_ */
