#ifndef MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_
#define MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_

#define FM_COMMAND_ADDRESS__PDU 		0xA5B2
#define FM_COMMAND_ADDRESS__MM_STEPPER_STATUS 	0x3726


#endif /* MAIN_FM_FM_COMMAND_ADDRESS_DEF_H_ */
